# Generated by Django 4.0.6 on 2022-07-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompleted',
            name='id',
        ),
        migrations.AlterField(
            model_name='taskcompleted',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.task'),
        ),
    ]
