# Generated by Django 4.0.6 on 2022-07-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_taskcompleted_id_alter_taskcompleted_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taskcompleted',
        ),
    ]
