# Generated by Django 4.0.6 on 2022-07-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_taskcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompleted',
            name='task',
        ),
        migrations.AddField(
            model_name='taskcompleted',
            name='task',
            field=models.ManyToManyField(to='base.task'),
        ),
    ]
