# Generated by Django 4.0.4 on 2022-07-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_taskcompleted_task_taskcompleted_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taskcompleted',
        ),
    ]
